name: flutter_base
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  bloc: ^9.0.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  iconsax_flutter: ^1.0.1
  go_router: ^16.1.0
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0
  logging: ^1.3.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  lottie: ^3.3.1
  meta: ^1.15.0
  intl: ^0.20.2
  dotted_border: ^3.1.0
  flutter_advanced_switch: ^3.1.0
  flutter_slidable: ^4.0.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_launcher_icons: ^0.14.4
  image_picker: ^1.2.1
  retrofit: ^4.9.0
  shared_preferences: ^2.3.2
  dio: ^5.9.0
  device_info_plus: ^12.2.0
  http: ^1.6.0
  flutter_appauth: ^11.0.0
  flutter_secure_storage: ^9.2.4
  jwt_decoder: ^2.0.1
  equatable: ^2.0.7
  webview_flutter: ^4.13.0

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  image_path: "assets/images/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  freezed: ^3.2.0
  json_serializable: ^6.9.5
  mockito: ^5.6.1

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 100